spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: HEADERS
          sample-external-service:
            logger-level: FULL
  application:
    name: logtest

server:
  port: 8888

service-name:
  feign-logger:
    should-not-log-request-headers: Authorization, jwt
    should-not-log-response-headers: jwt

sample-external-service:
  url: http://localhost:8888

logging:
  level:
    com.logtest.feignlogger: DEBUG
    feign.Logger: DEBUG
    org.springframework.cloud.openfeign: DEBUG